-- Másold be ezt a Supabase SQL Editorba és futtasd le (Run).

-- 1. Töröljük a táblát ha már létezik (hogy tiszta lappal kezdjünk), vagy hagyd ki ezt a sort ha meg akarod tartani az adatokat.
-- DROP TABLE IF EXISTS leaderboard;

-- 2. Tábla létrehozása
CREATE TABLE IF NOT EXISTS leaderboard (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  score integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Row Level Security (RLS) bekapcsolása - ez kötelező Supabase-nél a szabályokhoz
ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY;

-- 4. Szabály: Mindenki olvashatja a ranglistát (SELECT)
CREATE POLICY "Public Read Access"
ON leaderboard FOR SELECT
USING (true);

-- 5. Szabály: Mindenki írhat a ranglistára (INSERT)
CREATE POLICY "Public Insert Access"
ON leaderboard FOR INSERT
WITH CHECK (true);

-- 6. Indexelés a gyorsabb rendezésért
CREATE INDEX IF NOT EXISTS leaderboard_score_idx ON leaderboard (score DESC);
