-- Futtasd le ezt a Supabase SQL Editorban.

-- 1. Tábla létrehozása (ha nem létezik)
CREATE TABLE IF NOT EXISTS leaderboard (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username text NOT NULL,
  score integer NOT NULL,
  created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. RLS (Biztonság) bekapcsolása
ALTER TABLE leaderboard ENABLE ROW LEVEL SECURITY;

-- 3. Régi szabályok törlése (tiszta lap)
DROP POLICY IF EXISTS "Public Read Access" ON leaderboard;
DROP POLICY IF EXISTS "Public Insert Access" ON leaderboard;
DROP POLICY IF EXISTS "Allow anon read" ON leaderboard;
DROP POLICY IF EXISTS "Allow anon insert" ON leaderboard;

-- 4. OLVASÁSI jog mindenkinek
CREATE POLICY "Allow anon read"
ON leaderboard FOR SELECT
TO anon
USING (true);

-- 5. ÍRÁSI jog mindenkinek
CREATE POLICY "Allow anon insert"
ON leaderboard FOR INSERT
TO anon
WITH CHECK (true);

-- 6. Indexelés
CREATE INDEX IF NOT EXISTS leaderboard_score_idx ON leaderboard (score DESC);
